name: reinstall
on:
  schedule:
    - cron: '20 7 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-reinstall
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Create new branch
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/heads/reinstall',
              sha: context.sha
            });

      - name: sync reinstall
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/bin456789/reinstall"
          source_branch: "main"
          destination_branch: "bin456789-reinstall"
          github_token: ${{ secrets.PAT }}
