name: CF-Workers-docker.io
on:
  schedule:
    - cron: '3 19 * * *'
  workflow_dispatch:
  repository_dispatch:
    types: sync-CF-Workers-docker.io
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Check if branch exists
        id: check_branch
        run: |
          if git show-ref --verify --quiet refs/heads/CF-Workers-docker.io; then
            echo "branch_exists=true" >> $GITHUB_ENV
          else:
            echo "branch_exists=false" >> $GITHUB_ENV
          fi

      - name: Delete existing branch
        if: ${{ env.branch_exists == 'true' }}
        run: |
          git push origin --delete CF-Workers-docker.io

      - name: Create new branch
        if: ${{ env.branch_exists == 'false' }}
        run: |
          git checkout -b CF-Workers-docker.io
          git push --set-upstream origin CF-Workers-docker.io

      - name: Sync branch
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/cmliu/CF-Workers-docker.io"
          source_branch: "main"
          destination_branch: "CF-Workers-docker.io"
          github_token: ${{ secrets.PAT }}
