name: Custom_OpenClash_Rules
on:
  schedule:
    - cron: '23 7 * * *'
  workflow_dispatch:
  repository_dispatch:
    types: sync-Custom_OpenClash_Rules
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Check if branch exists
        id: check_branch
        run: |
          if git show-ref --verify --quiet refs/heads/Custom_OpenClash_Rules; then
            echo "branch_exists=true" >> $GITHUB_ENV
          else:
            echo "branch_exists=false" >> $GITHUB_ENV
          fi

      - name: Delete existing branch
        if: ${{ env.branch_exists == 'true' }}
        run: |
          git push origin --delete Custom_OpenClash_Rules

      - name: Create new branch
        if: ${{ env.branch_exists == 'false' }}
        run: |
          git checkout -b Custom_OpenClash_Rules
          git push --set-upstream origin Custom_OpenClash_Rules

      - name: Sync branch
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/Aethersailor/Custom_OpenClash_Rules"
          source_branch: "main"
          destination_branch: "Custom_OpenClash_Rules"
          github_token: ${{ secrets.PAT }}
